name = xp_redo
title = XP Redo
description = Player experience management
depends = default
optional_depends = areas, qos, protector, doors, mobs_redo, mobs_animal, mobs_monster, mesecons_mvps, hudbars, screwdriver, woodcutting
